require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Photog::PhotographersController do

  # This should return the minimal set of attributes required to create a valid
  # Photographer. As you add validations to Photographer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all photographers as @photographers" do
      photographer = Photographer.create! valid_attributes
      get :index
      assigns(:photographers).should eq([photographer])
    end
  end

  describe "GET show" do
    it "assigns the requested photographer as @photographer" do
      photographer = Photographer.create! valid_attributes
      get :show, :id => photographer.id.to_s
      assigns(:photographer).should eq(photographer)
    end
  end

  describe "GET new" do
    it "assigns a new photographer as @photographer" do
      get :new
      assigns(:photographer).should be_a_new(Photographer)
    end
  end

  describe "GET edit" do
    it "assigns the requested photographer as @photographer" do
      photographer = Photographer.create! valid_attributes
      get :edit, :id => photographer.id.to_s
      assigns(:photographer).should eq(photographer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Photographer" do
        expect {
          post :create, :photographer => valid_attributes
        }.to change(Photographer, :count).by(1)
      end

      it "assigns a newly created photographer as @photographer" do
        post :create, :photographer => valid_attributes
        assigns(:photographer).should be_a(Photographer)
        assigns(:photographer).should be_persisted
      end

      it "redirects to the created photographer" do
        post :create, :photographer => valid_attributes
        response.should redirect_to(Photographer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved photographer as @photographer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Photographer.any_instance.stub(:save).and_return(false)
        post :create, :photographer => {}
        assigns(:photographer).should be_a_new(Photographer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Photographer.any_instance.stub(:save).and_return(false)
        post :create, :photographer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested photographer" do
        photographer = Photographer.create! valid_attributes
        # Assuming there are no other photographers in the database, this
        # specifies that the Photographer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Photographer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => photographer.id, :photographer => {'these' => 'params'}
      end

      it "assigns the requested photographer as @photographer" do
        photographer = Photographer.create! valid_attributes
        put :update, :id => photographer.id, :photographer => valid_attributes
        assigns(:photographer).should eq(photographer)
      end

      it "redirects to the photographer" do
        photographer = Photographer.create! valid_attributes
        put :update, :id => photographer.id, :photographer => valid_attributes
        response.should redirect_to(photographer)
      end
    end

    describe "with invalid params" do
      it "assigns the photographer as @photographer" do
        photographer = Photographer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Photographer.any_instance.stub(:save).and_return(false)
        put :update, :id => photographer.id.to_s, :photographer => {}
        assigns(:photographer).should eq(photographer)
      end

      it "re-renders the 'edit' template" do
        photographer = Photographer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Photographer.any_instance.stub(:save).and_return(false)
        put :update, :id => photographer.id.to_s, :photographer => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested photographer" do
      photographer = Photographer.create! valid_attributes
      expect {
        delete :destroy, :id => photographer.id.to_s
      }.to change(Photographer, :count).by(-1)
    end

    it "redirects to the photographers list" do
      photographer = Photographer.create! valid_attributes
      delete :destroy, :id => photographer.id.to_s
      response.should redirect_to(photographers_url)
    end
  end

end
