require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PortfoliosController do

  # This should return the minimal set of attributes required to create a valid
  # Portfolio. As you add validations to Portfolio, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all portfolios as @portfolios" do
      portfolio = Portfolio.create! valid_attributes
      get :index
      assigns(:portfolios).should eq([portfolio])
    end
  end

  describe "GET show" do
    it "assigns the requested portfolio as @portfolio" do
      portfolio = Portfolio.create! valid_attributes
      get :show, :id => portfolio.id.to_s
      assigns(:portfolio).should eq(portfolio)
    end
  end

  describe "GET new" do
    it "assigns a new portfolio as @portfolio" do
      get :new
      assigns(:portfolio).should be_a_new(Portfolio)
    end
  end

  describe "GET edit" do
    it "assigns the requested portfolio as @portfolio" do
      portfolio = Portfolio.create! valid_attributes
      get :edit, :id => portfolio.id.to_s
      assigns(:portfolio).should eq(portfolio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Portfolio" do
        expect {
          post :create, :portfolio => valid_attributes
        }.to change(Portfolio, :count).by(1)
      end

      it "assigns a newly created portfolio as @portfolio" do
        post :create, :portfolio => valid_attributes
        assigns(:portfolio).should be_a(Portfolio)
        assigns(:portfolio).should be_persisted
      end

      it "redirects to the created portfolio" do
        post :create, :portfolio => valid_attributes
        response.should redirect_to(Portfolio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved portfolio as @portfolio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Portfolio.any_instance.stub(:save).and_return(false)
        post :create, :portfolio => {}
        assigns(:portfolio).should be_a_new(Portfolio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Portfolio.any_instance.stub(:save).and_return(false)
        post :create, :portfolio => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested portfolio" do
        portfolio = Portfolio.create! valid_attributes
        # Assuming there are no other portfolios in the database, this
        # specifies that the Portfolio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Portfolio.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => portfolio.id, :portfolio => {'these' => 'params'}
      end

      it "assigns the requested portfolio as @portfolio" do
        portfolio = Portfolio.create! valid_attributes
        put :update, :id => portfolio.id, :portfolio => valid_attributes
        assigns(:portfolio).should eq(portfolio)
      end

      it "redirects to the portfolio" do
        portfolio = Portfolio.create! valid_attributes
        put :update, :id => portfolio.id, :portfolio => valid_attributes
        response.should redirect_to(portfolio)
      end
    end

    describe "with invalid params" do
      it "assigns the portfolio as @portfolio" do
        portfolio = Portfolio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Portfolio.any_instance.stub(:save).and_return(false)
        put :update, :id => portfolio.id.to_s, :portfolio => {}
        assigns(:portfolio).should eq(portfolio)
      end

      it "re-renders the 'edit' template" do
        portfolio = Portfolio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Portfolio.any_instance.stub(:save).and_return(false)
        put :update, :id => portfolio.id.to_s, :portfolio => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested portfolio" do
      portfolio = Portfolio.create! valid_attributes
      expect {
        delete :destroy, :id => portfolio.id.to_s
      }.to change(Portfolio, :count).by(-1)
    end

    it "redirects to the portfolios list" do
      portfolio = Portfolio.create! valid_attributes
      delete :destroy, :id => portfolio.id.to_s
      response.should redirect_to(portfolios_url)
    end
  end

end
